#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-nifi-registry
Version  : 0.1.0
Release  : 1
URL      : https://github.com/apache/nifi-registry/archive/rel/nifi-registry-0.1.0.tar.gz
Source0  : https://github.com/apache/nifi-registry/archive/rel/nifi-registry-0.1.0.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/nifi/registry/nifi-registry-data-model/0.1.0/nifi-registry-data-model-0.1.0.jar
Source2  : https://repo1.maven.org/maven2/org/apache/nifi/registry/nifi-registry-data-model/0.1.0/nifi-registry-data-model-0.1.0.pom
Source3  : https://repo1.maven.org/maven2/org/apache/nifi/registry/nifi-registry/0.1.0/nifi-registry-0.1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: mvn-nifi-registry-data = %{version}-%{release}
Requires: mvn-nifi-registry-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
<!--
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
# Apache NiFi Registry

%package data
Summary: data components for the mvn-nifi-registry package.
Group: Data

%description data
data components for the mvn-nifi-registry package.


%package license
Summary: license components for the mvn-nifi-registry package.
Group: Default

%description license
license components for the mvn-nifi-registry package.


%prep
%setup -q -n nifi-registry-rel-nifi-registry-0.1.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-nifi-registry
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-nifi-registry/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-nifi-registry/NOTICE
cp nifi-registry-assembly/LICENSE %{buildroot}/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-assembly_LICENSE
cp nifi-registry-assembly/NOTICE %{buildroot}/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-assembly_NOTICE
cp nifi-registry-docs/LICENSE %{buildroot}/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-docs_LICENSE
cp nifi-registry-docs/NOTICE %{buildroot}/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-docs_NOTICE
cp nifi-registry-web-api/src/main/resources/META-INF/LICENSE %{buildroot}/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-web-api_src_main_resources_META-INF_LICENSE
cp nifi-registry-web-api/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-web-api_src_main_resources_META-INF_NOTICE
cp nifi-registry-web-docs/src/main/resources/META-INF/LICENSE %{buildroot}/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-web-docs_src_main_resources_META-INF_LICENSE
cp nifi-registry-web-docs/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-web-docs_src_main_resources_META-INF_NOTICE
cp nifi-registry-web-ui/src/main/resources/META-INF/LICENSE %{buildroot}/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-web-ui_src_main_resources_META-INF_LICENSE
cp nifi-registry-web-ui/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-web-ui_src_main_resources_META-INF_NOTICE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/registry/nifi-registry-data-model/0.1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/registry/nifi-registry-data-model/0.1.0/nifi-registry-data-model-0.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/registry/nifi-registry-data-model/0.1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/registry/nifi-registry-data-model/0.1.0/nifi-registry-data-model-0.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/registry/nifi-registry/0.1.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/registry/nifi-registry/0.1.0/nifi-registry-0.1.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/nifi/registry/nifi-registry-data-model/0.1.0/nifi-registry-data-model-0.1.0.jar
/usr/share/java/.m2/repository/org/apache/nifi/registry/nifi-registry-data-model/0.1.0/nifi-registry-data-model-0.1.0.pom
/usr/share/java/.m2/repository/org/apache/nifi/registry/nifi-registry/0.1.0/nifi-registry-0.1.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-nifi-registry/LICENSE
/usr/share/package-licenses/mvn-nifi-registry/NOTICE
/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-assembly_LICENSE
/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-assembly_NOTICE
/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-docs_LICENSE
/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-docs_NOTICE
/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-web-api_src_main_resources_META-INF_LICENSE
/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-web-api_src_main_resources_META-INF_NOTICE
/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-web-docs_src_main_resources_META-INF_LICENSE
/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-web-docs_src_main_resources_META-INF_NOTICE
/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-web-ui_src_main_resources_META-INF_LICENSE
/usr/share/package-licenses/mvn-nifi-registry/nifi-registry-web-ui_src_main_resources_META-INF_NOTICE
